# Generated by Django 3.1.2 on 2020-12-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
